# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-06-15T04:48:16+00:00

from __future__ import annotations

from typing import Any, Literal, TypeAlias, TypedDict

from typing_extensions import NotRequired

WikiLintIssueSeverity: TypeAlias = Literal['info', 'warning', 'error']


WikiLintIssueType: TypeAlias = Literal[
    'orphan_page',
    'broken_link',
    'stale_ref',
    'missing_cross_ref',
    'empty_content',
    'duplicate_slug',
]


class ConnectorMetadata(TypedDict):
    auth_type: NotRequired[str]
    capabilities: NotRequired[list[str]]
    description: NotRequired[str]
    icon: NotRequired[str]
    name: NotRequired[str]
    priority: NotRequired[int]
    type: NotRequired[str]


ErrorCode: TypeAlias = Literal[
    1000,
    1001,
    1002,
    1003,
    1004,
    1005,
    1006,
    1007,
    1008,
    1009,
    1010,
    2000,
    2001,
    2002,
    2003,
    2004,
    2100,
    2101,
    2102,
    2103,
    2200,
    2201,
]


class DocProfile(TypedDict):
    all_caps_short_line_count: NotRequired[int]
    avg_line_len: NotRequired[float]
    blank_paragraph_breaks: NotRequired[int]
    chinese_chapter_count: NotRequired[int]
    code_ratio: NotRequired[float]
    detected_langs: NotRequired[list[str]]
    english_chapter_count: NotRequired[int]
    form_feed_count: NotRequired[int]
    german_chapter_count: NotRequired[int]
    has_code: NotRequired[bool]
    has_tables: NotRequired[bool]
    md_heading_counts: NotRequired[dict[str, int]]
    md_heading_total: NotRequired[int]
    numbered_section_count: NotRequired[int]
    repeated_footer_count: NotRequired[int]
    std_line_len: NotRequired[float]
    total_chars: NotRequired[int]
    total_lines: NotRequired[int]
    visual_sep_count: NotRequired[int]


StrategyTier: TypeAlias = Literal['heading', 'heuristic', 'legacy']


class TierRejection(TypedDict):
    reason: NotRequired[str]
    tier: NotRequired[StrategyTier]


class ASRConfig(TypedDict):
    enabled: NotRequired[bool]
    language: NotRequired[str]
    model_id: NotRequired[str]


AnswerStrategy: TypeAlias = Literal['all', 'random']


AuditAction: TypeAlias = Literal[
    'rbac.member_added',
    'rbac.member_removed',
    'rbac.member_role_changed',
    'rbac.member_left',
    'rbac.access_denied',
    'rbac.invitation_sent',
    'rbac.invitation_accepted',
    'rbac.invitation_declined',
    'rbac.invitation_revoked',
    'rbac.invitation_expired',
    'vector_store.created',
    'vector_store.updated',
    'vector_store.deleted',
    'opensearch.index_created',
    'opensearch.index_deleted',
    'opensearch.reindex_executed',
    'system.setting_changed',
    'system.admin_promoted',
    'system.admin_revoked',
]


AuditOutcome: TypeAlias = Literal['success', 'denied']


class COSEngineConfig(TypedDict):
    app_id: NotRequired[str]
    bucket_name: NotRequired[str]
    path_prefix: NotRequired[str]
    region: NotRequired[str]
    secret_id: NotRequired[str]
    secret_key: NotRequired[str]


class ChatHistoryConfig(TypedDict):
    embedding_model_id: NotRequired[str]
    enabled: NotRequired[bool]
    knowledge_base_id: NotRequired[str]


class ConnectionConfig(TypedDict):
    addr: NotRequired[str]
    api_key: NotRequired[str]
    database: NotRequired[str]
    grpc_address: NotRequired[str]
    host: NotRequired[str]
    http_port: NotRequired[int]
    insecure_skip_verify: NotRequired[bool]
    password: NotRequired[str]
    port: NotRequired[int]
    scheme: NotRequired[str]
    use_default_connection: NotRequired[bool]
    use_tls: NotRequired[bool]
    username: NotRequired[str]
    version: NotRequired[str]


ContextCompressionStrategy: TypeAlias = Literal['sliding_window', 'smart']


class ContextConfig(TypedDict):
    compression_strategy: NotRequired[ContextCompressionStrategy]
    max_tokens: NotRequired[int]
    recent_message_count: NotRequired[int]
    summarize_threshold: NotRequired[int]


class CreateOrganizationRequest(TypedDict):
    avatar: NotRequired[str]
    description: NotRequired[str]
    invite_code_validity_days: NotRequired[int]
    member_limit: NotRequired[int]
    name: str


class CustomAgentConfig(TypedDict):
    agent_mode: NotRequired[str]
    agent_type: NotRequired[str]
    allowed_tools: NotRequired[list[str]]
    asr_model_id: NotRequired[str]
    audio_upload_enabled: NotRequired[bool]
    context_template: NotRequired[str]
    context_template_id: NotRequired[str]
    data_analysis_enabled: NotRequired[bool]
    embedding_top_k: NotRequired[int]
    enable_query_expansion: NotRequired[bool]
    enable_rewrite: NotRequired[bool]
    fallback_prompt: NotRequired[str]
    fallback_response: NotRequired[str]
    fallback_strategy: NotRequired[str]
    faq_direct_answer_threshold: NotRequired[float]
    faq_priority_enabled: NotRequired[bool]
    faq_score_boost: NotRequired[float]
    history_turns: NotRequired[int]
    image_storage_provider: NotRequired[str]
    image_upload_enabled: NotRequired[bool]
    intent_prompts: NotRequired[dict[str, str]]
    kb_selection_mode: NotRequired[str]
    keyword_threshold: NotRequired[float]
    knowledge_bases: NotRequired[list[str]]
    llm_call_timeout: NotRequired[int]
    max_completion_tokens: NotRequired[int]
    max_iterations: NotRequired[int]
    mcp_selection_mode: NotRequired[str]
    mcp_services: NotRequired[list[str]]
    model_id: NotRequired[str]
    multi_turn_enabled: NotRequired[bool]
    query_understand_model_id: NotRequired[str]
    rerank_model_id: NotRequired[str]
    rerank_threshold: NotRequired[float]
    rerank_top_k: NotRequired[int]
    retain_retrieval_history: NotRequired[bool]
    retrieve_kb_only_when_mentioned: NotRequired[bool]
    rewrite_prompt_system: NotRequired[str]
    rewrite_prompt_user: NotRequired[str]
    selected_skills: NotRequired[list[str]]
    skills_selection_mode: NotRequired[str]
    suggested_prompts: NotRequired[list[str]]
    supported_file_types: NotRequired[list[str]]
    system_prompt: NotRequired[str]
    system_prompt_id: NotRequired[str]
    temperature: NotRequired[float]
    thinking: NotRequired[bool]
    vector_threshold: NotRequired[float]
    vlm_model_id: NotRequired[str]
    web_fetch_enabled: NotRequired[bool]
    web_fetch_top_n: NotRequired[int]
    web_search_enabled: NotRequired[bool]
    web_search_max_results: NotRequired[int]
    web_search_provider_id: NotRequired[str]


class EmbeddingParameters(TypedDict):
    dimension: NotRequired[int]
    truncate_prompt_tokens: NotRequired[int]


class FAQEntryFieldsUpdate(TypedDict):
    is_enabled: NotRequired[bool]
    is_recommended: NotRequired[bool]
    tag_id: NotRequired[int]


class FAQEntryPayload(TypedDict):
    answer_strategy: NotRequired[AnswerStrategy]
    answers: NotRequired[list[str]]
    id: NotRequired[int]
    is_enabled: NotRequired[bool]
    is_recommended: NotRequired[bool]
    negative_questions: NotRequired[list[str]]
    similar_questions: NotRequired[list[str]]
    standard_question: str
    tag_id: NotRequired[int]
    tag_name: NotRequired[str]


FAQIndexMode: TypeAlias = Literal['question_only', 'question_answer']


FAQQuestionIndexMode: TypeAlias = Literal['combined', 'separate']


class FAQSearchRequest(TypedDict):
    first_priority_tag_ids: NotRequired[list[int]]
    match_count: NotRequired[int]
    only_recommended: NotRequired[bool]
    query_text: str
    second_priority_tag_ids: NotRequired[list[int]]
    vector_threshold: NotRequired[float]


class GraphNode(TypedDict):
    attributes: NotRequired[list[str]]
    chunks: NotRequired[list[str]]
    name: NotRequired[str]


class GraphRelation(TypedDict):
    node1: NotRequired[str]
    node2: NotRequired[str]
    type: NotRequired[str]


class ImageProcessingConfig(TypedDict):
    model_id: NotRequired[str]


class IndexConfig(TypedDict):
    buckets_num: NotRequired[int]
    collection_name: NotRequired[str]
    collection_prefix: NotRequired[str]
    desired_shard_count: NotRequired[int]
    hnsw_ef_construction: NotRequired[int]
    hnsw_ef_search: NotRequired[int]
    hnsw_m: NotRequired[int]
    index_name: NotRequired[str]
    knn_engine: NotRequired[str]
    number_of_replicas: NotRequired[int]
    number_of_shards: NotRequired[int]
    replica_number: NotRequired[int]
    replication_factor: NotRequired[int]
    replication_num: NotRequired[int]
    shard_number: NotRequired[int]
    shards_num: NotRequired[int]


class IndexingStrategy(TypedDict):
    graph_enabled: NotRequired[bool]
    keyword_enabled: NotRequired[bool]
    vector_enabled: NotRequired[bool]
    wiki_enabled: NotRequired[bool]


class JoinOrganizationRequest(TypedDict):
    invite_code: str


KBCloneTaskStatus: TypeAlias = Literal['pending', 'processing', 'completed', 'failed']


class KS3EngineConfig(TypedDict):
    access_key: NotRequired[str]
    bucket_name: NotRequired[str]
    endpoint: NotRequired[str]
    path_prefix: NotRequired[str]
    region: NotRequired[str]
    secret_key: NotRequired[str]


class KnowledgeBaseShareResponse(TypedDict):
    chunk_count: NotRequired[int]
    created_at: NotRequired[str]
    id: NotRequired[str]
    knowledge_base_id: NotRequired[str]
    knowledge_base_name: NotRequired[str]
    knowledge_base_type: NotRequired[str]
    knowledge_count: NotRequired[int]
    my_permission: NotRequired[str]
    my_role_in_org: NotRequired[str]
    organization_id: NotRequired[str]
    organization_name: NotRequired[str]
    permission: NotRequired[str]
    require_approval: NotRequired[bool]
    shared_by_user_id: NotRequired[str]
    shared_by_username: NotRequired[str]
    source_tenant_id: NotRequired[int]


class KnowledgeMoveProgress(TypedDict):
    created_at: NotRequired[int]
    error: NotRequired[str]
    failed: NotRequired[int]
    message: NotRequired[str]
    processed: NotRequired[int]
    progress: NotRequired[int]
    source_kb_id: NotRequired[str]
    status: NotRequired[KBCloneTaskStatus]
    target_kb_id: NotRequired[str]
    task_id: NotRequired[str]
    total: NotRequired[int]
    updated_at: NotRequired[int]


class ListSharesResponse(TypedDict):
    shares: NotRequired[list[KnowledgeBaseShareResponse]]
    total: NotRequired[int]


class LocalEngineConfig(TypedDict):
    path_prefix: NotRequired[str]


class LoginRequest(TypedDict):
    email: str
    password: str


class MCPAdvancedConfig(TypedDict):
    retry_count: NotRequired[int]
    retry_delay: NotRequired[int]
    timeout: NotRequired[int]


class MCPAuthConfig(TypedDict):
    api_key: NotRequired[str]
    custom_headers: NotRequired[dict[str, str]]
    token: NotRequired[str]


MCPEnvVars: TypeAlias = dict[str, str]


MCPHeaders: TypeAlias = dict[str, str]


class MCPStdioConfig(TypedDict):
    args: NotRequired[list[str]]
    command: NotRequired[str]


MCPTransportType: TypeAlias = Literal['sse', 'http-streamable', 'stdio']


MatchType: TypeAlias = Literal[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


class MentionedItem(TypedDict):
    id: NotRequired[str]
    kb_type: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[str]


class MessageAttachment(TypedDict):
    content: NotRequired[str]
    file_name: NotRequired[str]
    file_size: NotRequired[int]
    file_type: NotRequired[str]
    is_truncated: NotRequired[bool]
    line_count: NotRequired[int]
    url: NotRequired[str]


class MessageImage(TypedDict):
    caption: NotRequired[str]
    url: NotRequired[str]


class MinIOEngineConfig(TypedDict):
    access_key_id: NotRequired[str]
    bucket_name: NotRequired[str]
    endpoint: NotRequired[str]
    mode: NotRequired[str]
    path_prefix: NotRequired[str]
    secret_access_key: NotRequired[str]
    use_ssl: NotRequired[bool]


class ModelParameters(TypedDict):
    api_key: NotRequired[str]
    app_id: NotRequired[str]
    app_secret: NotRequired[str]
    base_url: NotRequired[str]
    custom_headers: NotRequired[dict[str, str]]
    embedding_parameters: NotRequired[EmbeddingParameters]
    extra_config: NotRequired[dict[str, str]]
    interface_type: NotRequired[str]
    parameter_size: NotRequired[str]
    provider: NotRequired[str]
    supports_vision: NotRequired[bool]


ModelSource: TypeAlias = Literal[
    'local',
    'remote',
    'aliyun',
    'zhipu',
    'volcengine',
    'deepseek',
    'hunyuan',
    'minimax',
    'openai',
    'gemini',
    'mimo',
    'siliconflow',
    'jina',
    'openrouter',
    'nvidia',
    'novita',
    'azure_openai',
]


ModelType: TypeAlias = Literal['Embedding', 'Rerank', 'KnowledgeQA', 'VLLM', 'ASR']


class OBSEngineConfig(TypedDict):
    access_key: NotRequired[str]
    bucket_name: NotRequired[str]
    endpoint: NotRequired[str]
    path_prefix: NotRequired[str]
    region: NotRequired[str]
    secret_key: NotRequired[str]
    use_ssl: NotRequired[bool]


class OIDCAuthURLResponse(TypedDict):
    authorization_url: NotRequired[str]
    provider_display_name: NotRequired[str]
    state: NotRequired[str]
    success: NotRequired[bool]


class OIDCConfigResponse(TypedDict):
    enabled: NotRequired[bool]
    provider_display_name: NotRequired[str]
    success: NotRequired[bool]


class OSSEngineConfig(TypedDict):
    access_key: NotRequired[str]
    bucket_name: NotRequired[str]
    endpoint: NotRequired[str]
    path_prefix: NotRequired[str]
    region: NotRequired[str]
    secret_key: NotRequired[str]
    temp_bucket_name: NotRequired[str]
    temp_region: NotRequired[str]
    use_temp_bucket: NotRequired[bool]


OrgMemberRole: TypeAlias = Literal['admin', 'editor', 'viewer']


class OrganizationMemberResponse(TypedDict):
    avatar: NotRequired[str]
    email: NotRequired[str]
    id: NotRequired[str]
    joined_at: NotRequired[str]
    representative_user_id: NotRequired[str]
    role: NotRequired[str]
    tenant_id: NotRequired[int]
    tenant_name: NotRequired[str]
    user_id: NotRequired[str]
    username: NotRequired[str]


class OrganizationResponse(TypedDict):
    agent_share_count: NotRequired[int]
    avatar: NotRequired[str]
    created_at: NotRequired[str]
    description: NotRequired[str]
    has_pending_upgrade: NotRequired[bool]
    id: NotRequired[str]
    invite_code: NotRequired[str]
    invite_code_expires_at: NotRequired[str]
    invite_code_validity_days: NotRequired[int]
    is_owner: NotRequired[bool]
    member_count: NotRequired[int]
    member_limit: NotRequired[int]
    my_role: NotRequired[str]
    name: NotRequired[str]
    owner_id: NotRequired[str]
    owner_tenant_id: NotRequired[int]
    pending_join_request_count: NotRequired[int]
    require_approval: NotRequired[bool]
    searchable: NotRequired[bool]
    share_count: NotRequired[int]
    updated_at: NotRequired[str]


class ParserEngineConfig(TypedDict):
    mineru_api_key: NotRequired[str]
    mineru_cloud_enable_formula: NotRequired[bool]
    mineru_cloud_enable_ocr: NotRequired[bool]
    mineru_cloud_enable_table: NotRequired[bool]
    mineru_cloud_language: NotRequired[str]
    mineru_cloud_model: NotRequired[str]
    mineru_enable_formula: NotRequired[bool]
    mineru_enable_ocr: NotRequired[bool]
    mineru_enable_table: NotRequired[bool]
    mineru_endpoint: NotRequired[str]
    mineru_language: NotRequired[str]
    mineru_model: NotRequired[str]
    mineru_vlm_server_url: NotRequired[str]
    odl_hybrid: NotRequired[str]
    odl_hybrid_fallback: NotRequired[bool]
    odl_hybrid_mode: NotRequired[str]
    odl_hybrid_url: NotRequired[str]
    odl_markdown_with_html: NotRequired[bool]
    paddleocr_vl_cloud_model: NotRequired[str]
    paddleocr_vl_cloud_token: NotRequired[str]
    paddleocr_vl_cloud_use_chart_recognition: NotRequired[bool]
    paddleocr_vl_cloud_use_seal_recognition: NotRequired[bool]
    paddleocr_vl_endpoint: NotRequired[str]
    paddleocr_vl_use_chart_recognition: NotRequired[bool]
    paddleocr_vl_use_seal_recognition: NotRequired[bool]


class ParserEngineRule(TypedDict):
    engine: NotRequired[str]
    file_types: NotRequired[list[str]]


class QuestionGenerationConfig(TypedDict):
    enabled: NotRequired[bool]
    question_count: NotRequired[int]


class RegisterRequest(TypedDict):
    email: str
    password: str
    username: str


class RequestRoleUpgradeRequest(TypedDict):
    message: NotRequired[str]
    requested_role: OrgMemberRole


class Resource(TypedDict):
    description: NotRequired[str]
    external_id: NotRequired[str]
    has_children: NotRequired[bool]
    metadata: NotRequired[dict[str, Any]]
    modified_at: NotRequired[str]
    name: NotRequired[str]
    parent_id: NotRequired[str]
    type: NotRequired[str]
    url: NotRequired[str]


class Agents(TypedDict):
    by_organization: NotRequired[dict[str, int]]


class KnowledgeBases(TypedDict):
    by_organization: NotRequired[dict[str, int]]


class ResourceCountsByOrgResponse(TypedDict):
    agents: NotRequired[Agents]
    knowledge_bases: NotRequired[KnowledgeBases]


class RetrievalConfig(TypedDict):
    embedding_top_k: NotRequired[int]
    keyword_threshold: NotRequired[float]
    rerank_model_id: NotRequired[str]
    rerank_threshold: NotRequired[float]
    rerank_top_k: NotRequired[int]
    rrf_k: NotRequired[int]
    rrf_keyword_weight: NotRequired[float]
    rrf_vector_weight: NotRequired[float]
    vector_threshold: NotRequired[float]


RetrieverEngineType: TypeAlias = Literal[
    'postgres',
    'elasticsearch',
    'infinity',
    'elasticfaiss',
    'qdrant',
    'milvus',
    'weaviate',
    'doris',
    'sqlite',
    'tencent_vectordb',
    'opensearch',
]


RetrieverType: TypeAlias = Literal['keywords', 'vector', 'websearch']


class ReviewJoinRequestRequest(TypedDict):
    approved: NotRequired[bool]
    message: NotRequired[str]
    role: NotRequired[OrgMemberRole]


class S3EngineConfig(TypedDict):
    access_key: NotRequired[str]
    bucket_name: NotRequired[str]
    endpoint: NotRequired[str]
    force_path_style: NotRequired[bool]
    path_prefix: NotRequired[str]
    region: NotRequired[str]
    secret_key: NotRequired[str]
    use_ssl: NotRequired[bool]


class SearchParams(TypedDict):
    disable_keywords_match: NotRequired[bool]
    disable_vector_match: NotRequired[bool]
    keyword_threshold: NotRequired[float]
    knowledge_base_ids: NotRequired[list[str]]
    knowledge_ids: NotRequired[list[str]]
    match_count: NotRequired[int]
    only_recommended: NotRequired[bool]
    query_embedding: NotRequired[list[float]]
    query_text: NotRequired[str]
    skip_context_enrichment: NotRequired[bool]
    tag_ids: NotRequired[list[str]]
    vector_threshold: NotRequired[float]


class SearchResult(TypedDict):
    chunk_index: NotRequired[int]
    chunk_metadata: NotRequired[list[int]]
    chunk_type: NotRequired[str]
    content: NotRequired[str]
    end_at: NotRequired[int]
    id: NotRequired[str]
    image_info: NotRequired[str]
    knowledge_base_id: NotRequired[str]
    knowledge_channel: NotRequired[str]
    knowledge_description: NotRequired[str]
    knowledge_filename: NotRequired[str]
    knowledge_id: NotRequired[str]
    knowledge_source: NotRequired[str]
    knowledge_title: NotRequired[str]
    match_type: NotRequired[MatchType]
    matched_content: NotRequired[str]
    metadata: NotRequired[dict[str, str]]
    parent_chunk_id: NotRequired[str]
    score: NotRequired[float]
    seq: NotRequired[int]
    start_at: NotRequired[int]
    sub_chunk_id: NotRequired[list[str]]


class SessionLastRequestState(TypedDict):
    agent_enabled: NotRequired[bool]
    agent_id: NotRequired[str]
    knowledge_base_ids: NotRequired[list[str]]
    knowledge_ids: NotRequired[list[str]]
    model_id: NotRequired[str]
    web_search_enabled: NotRequired[bool]


class ShareKnowledgeBaseRequest(TypedDict):
    organization_id: str
    permission: OrgMemberRole


class StorageConfig(TypedDict):
    app_id: NotRequired[str]
    bucket_name: NotRequired[str]
    endpoint: NotRequired[str]
    force_path_style: NotRequired[bool]
    path_prefix: NotRequired[str]
    provider: NotRequired[str]
    region: NotRequired[str]
    secret_id: NotRequired[str]
    secret_key: NotRequired[str]
    use_ssl: NotRequired[bool]


class StorageProviderConfig(TypedDict):
    provider: NotRequired[str]


class SubmitJoinRequestRequest(TypedDict):
    invite_code: str
    message: NotRequired[str]
    role: NotRequired[OrgMemberRole]


class SyncLog(TypedDict):
    created_at: NotRequired[str]
    data_source_id: NotRequired[str]
    error_message: NotRequired[str]
    finished_at: NotRequired[str]
    id: NotRequired[str]
    items_created: NotRequired[int]
    items_deleted: NotRequired[int]
    items_failed: NotRequired[int]
    items_skipped: NotRequired[int]
    items_total: NotRequired[int]
    items_updated: NotRequired[int]
    result: NotRequired[list[int]]
    started_at: NotRequired[str]
    status: NotRequired[str]
    tenant_id: NotRequired[int]
    updated_at: NotRequired[str]


class SystemSetting(TypedDict):
    category: NotRequired[str]
    created_at: NotRequired[str]
    description: NotRequired[str]
    enum: NotRequired[list[str]]
    id: NotRequired[int]
    is_secret: NotRequired[bool]
    key: NotRequired[str]
    last_modified_by: NotRequired[str]
    last_modified_by_name: NotRequired[str]
    requires_restart: NotRequired[bool]
    updated_at: NotRequired[str]
    value: NotRequired[list[int]]
    value_type: NotRequired[str]


class TOSEngineConfig(TypedDict):
    access_key: NotRequired[str]
    bucket_name: NotRequired[str]
    endpoint: NotRequired[str]
    path_prefix: NotRequired[str]
    region: NotRequired[str]
    secret_key: NotRequired[str]


TenantRole: TypeAlias = Literal['owner', 'admin', 'contributor', 'viewer']


ToolCallMetadata: TypeAlias = dict[str, list[int]]


class ToolResult(TypedDict):
    data: NotRequired[dict[str, Any]]
    error: NotRequired[str]
    images: NotRequired[list[str]]
    output: NotRequired[str]
    success: NotRequired[bool]


class UpdateMemberRoleRequest(TypedDict):
    role: OrgMemberRole


class UpdateOrganizationRequest(TypedDict):
    avatar: NotRequired[str]
    description: NotRequired[str]
    invite_code_validity_days: NotRequired[int]
    member_limit: NotRequired[int]
    name: NotRequired[str]
    require_approval: NotRequired[bool]
    searchable: NotRequired[bool]


class UpdateSharePermissionRequest(TypedDict):
    permission: OrgMemberRole


class UserPreferences(TypedDict):
    enable_memory: NotRequired[bool]
    last_active_tenant_id: NotRequired[int]


class VLMConfig(TypedDict):
    api_key: NotRequired[str]
    base_url: NotRequired[str]
    enabled: NotRequired[bool]
    interface_type: NotRequired[str]
    model_id: NotRequired[str]
    model_name: NotRequired[str]


class WeKnoraCloudCredentials(TypedDict):
    app_id: NotRequired[str]
    app_secret: NotRequired[str]


class WebSearchConfig(TypedDict):
    api_key: NotRequired[str]
    blacklist: NotRequired[list[str]]
    compression_method: NotRequired[str]
    document_fragments: NotRequired[int]
    embedding_dimension: NotRequired[int]
    embedding_model_id: NotRequired[str]
    include_date: NotRequired[bool]
    max_results: NotRequired[int]
    provider: NotRequired[str]
    proxy_url: NotRequired[str]
    rerank_model_id: NotRequired[str]


class WebSearchProviderParameters(TypedDict):
    api_key: NotRequired[str]
    base_url: NotRequired[str]
    engine_id: NotRequired[str]
    extra_config: NotRequired[dict[str, str]]
    proxy_url: NotRequired[str]


WebSearchProviderType: TypeAlias = Literal[
    'bing', 'google', 'duckduckgo', 'tavily', 'ollama', 'baidu', 'searxng'
]


WikiExtractionGranularity: TypeAlias = Literal['focused', 'standard', 'exhaustive']


class WikiGraphEdge(TypedDict):
    source: NotRequired[str]
    target: NotRequired[str]


class WikiGraphMeta(TypedDict):
    center: NotRequired[str]
    depth: NotRequired[int]
    mode: NotRequired[str]
    returned: NotRequired[int]
    total: NotRequired[int]
    truncated: NotRequired[bool]


class WikiGraphNode(TypedDict):
    link_count: NotRequired[int]
    page_type: NotRequired[str]
    slug: NotRequired[str]
    title: NotRequired[str]


class WikiIndexEntry(TypedDict):
    slug: NotRequired[str]
    summary: NotRequired[str]
    title: NotRequired[str]


class WikiIndexGroup(TypedDict):
    items: NotRequired[list[WikiIndexEntry]]
    next_cursor: NotRequired[str]
    total: NotRequired[int]
    type: NotRequired[str]


class WikiIndexResponse(TypedDict):
    groups: NotRequired[list[WikiIndexGroup]]
    intro: NotRequired[str]
    version: NotRequired[int]


class WikiLogPageRef(TypedDict):
    slug: NotRequired[str]
    title: NotRequired[str]


class DeletedAt(TypedDict):
    time: NotRequired[str]
    valid: NotRequired[bool]


class AddFavoriteRequest(TypedDict):
    id: NotRequired[str]
    type: NotRequired[str]


class BatchDeleteKnowledgeRequest(TypedDict):
    ids: list[str]
    kb_id: str


class CopyKnowledgeBaseRequest(TypedDict):
    source_id: str
    target_id: NotRequired[str]
    task_id: NotRequired[str]


class CreateAgentRequest(TypedDict):
    avatar: NotRequired[str]
    config: NotRequired[CustomAgentConfig]
    description: NotRequired[str]
    name: str


class CreateModelRequest(TypedDict):
    description: NotRequired[str]
    display_name: NotRequired[str]
    name: str
    parameters: ModelParameters
    source: ModelSource
    type: ModelType


class CreateStoreRequest(TypedDict):
    connection_config: ConnectionConfig
    engine_type: RetrieverEngineType
    index_config: NotRequired[IndexConfig]
    name: str


class DeleteTagRequest(TypedDict):
    exclude_ids: NotRequired[list[int]]


class EvaluationRequest(TypedDict):
    chat_id: NotRequired[str]
    dataset_id: NotRequired[str]
    knowledge_base_id: NotRequired[str]
    rerank_id: NotRequired[str]


class FabriTextRequest(TypedDict):
    model_id: str
    tags: NotRequired[list[str]]


class GetSystemInfoResponse(TypedDict):
    build_time: NotRequired[str]
    commit_id: NotRequired[str]
    db_migration_error: NotRequired[str]
    db_version: NotRequired[str]
    edition: NotRequired[str]
    go_version: NotRequired[str]
    graph_database_engine: NotRequired[str]
    keyword_index_engine: NotRequired[str]
    minio_enabled: NotRequired[bool]
    started_at: NotRequired[str]
    uptime_seconds: NotRequired[int]
    vector_store_engine: NotRequired[str]
    version: NotRequired[str]


class DocumentSplitting(TypedDict):
    chunkOverlap: NotRequired[int]
    chunkSize: int
    separators: list[str]


class Embedding(TypedDict):
    apiKey: NotRequired[str]
    baseUrl: NotRequired[str]
    dimension: NotRequired[int]
    modelName: str
    source: str


class Llm(TypedDict):
    apiKey: NotRequired[str]
    baseUrl: NotRequired[str]
    modelName: str
    source: str


class Cos(TypedDict):
    appId: NotRequired[str]
    bucketName: NotRequired[str]
    pathPrefix: NotRequired[str]
    region: NotRequired[str]
    secretId: NotRequired[str]
    secretKey: NotRequired[str]


class Minio(TypedDict):
    bucketName: NotRequired[str]
    pathPrefix: NotRequired[str]


class Vlm(TypedDict):
    apiKey: NotRequired[str]
    baseUrl: NotRequired[str]
    interfaceType: NotRequired[str]
    modelName: NotRequired[str]


class Multimodal(TypedDict):
    cos: NotRequired[Cos]
    enabled: NotRequired[bool]
    minio: NotRequired[Minio]
    storageType: NotRequired[str]
    vlm: NotRequired[Vlm]


class Node(TypedDict):
    attributes: NotRequired[list[str]]
    name: NotRequired[str]


class Relation(TypedDict):
    node1: NotRequired[str]
    node2: NotRequired[str]
    type: NotRequired[str]


class NodeExtract(TypedDict):
    enabled: NotRequired[bool]
    nodes: NotRequired[list[Node]]
    relations: NotRequired[list[Relation]]
    tags: NotRequired[list[str]]
    text: NotRequired[str]


class QuestionGeneration(TypedDict):
    enabled: NotRequired[bool]
    questionCount: NotRequired[int]


class Rerank(TypedDict):
    apiKey: NotRequired[str]
    baseUrl: NotRequired[str]
    enabled: NotRequired[bool]
    modelName: NotRequired[str]


class InitializationRequest(TypedDict):
    documentSplitting: DocumentSplitting
    embedding: Embedding
    llm: Llm
    multimodal: NotRequired[Multimodal]
    nodeExtract: NotRequired[NodeExtract]
    questionGeneration: NotRequired[QuestionGeneration]
    rerank: NotRequired[Rerank]


class DocumentSplitting1(TypedDict):
    childChunkSize: NotRequired[int]
    chunkOverlap: NotRequired[int]
    chunkSize: NotRequired[int]
    enableParentChild: NotRequired[bool]
    languages: NotRequired[list[str]]
    parentChunkSize: NotRequired[int]
    parserEngineRules: NotRequired[list[ParserEngineRule]]
    separators: NotRequired[list[str]]
    strategy: NotRequired[str]
    tokenLimit: NotRequired[int]


class Multimodal1(TypedDict):
    enabled: NotRequired[bool]


class NodeExtract1(TypedDict):
    enabled: NotRequired[bool]
    nodes: NotRequired[list[GraphNode]]
    relations: NotRequired[list[GraphRelation]]
    tags: NotRequired[list[str]]
    text: NotRequired[str]


class KBModelConfigRequest(TypedDict):
    asr_config: NotRequired[ASRConfig]
    documentSplitting: NotRequired[DocumentSplitting1]
    embeddingModelId: NotRequired[str]
    llmModelId: str
    multimodal: NotRequired[Multimodal1]
    nodeExtract: NotRequired[NodeExtract1]
    questionGeneration: NotRequired[QuestionGeneration]
    storageProvider: NotRequired[str]
    vlm_config: NotRequired[VLMConfig]


class ModelTestRequest(TypedDict):
    apiKey: NotRequired[str]
    appSecret: NotRequired[str]
    baseUrl: NotRequired[str]
    customHeaders: NotRequired[dict[str, str]]
    dimension: NotRequired[int]
    extraConfig: NotRequired[dict[str, str]]
    interfaceType: NotRequired[str]
    modelId: NotRequired[str]
    modelName: str
    provider: NotRequired[str]
    source: NotRequired[str]


class MoveKnowledgeRequest(TypedDict):
    knowledge_ids: list[str]
    mode: Literal['reuse_vectors', 'reparse']
    source_kb_id: str
    target_kb_id: str


class MoveKnowledgeResponse(TypedDict):
    knowledge_count: NotRequired[int]
    message: NotRequired[str]
    source_kb_id: NotRequired[str]
    target_kb_id: NotRequired[str]
    task_id: NotRequired[str]


class PreviewChunkResult(TypedDict):
    content: NotRequired[str]
    context_header: NotRequired[str]
    end: NotRequired[int]
    seq: NotRequired[int]
    size_chars: NotRequired[int]
    size_tokens_approx: NotRequired[int]
    start: NotRequired[int]


class PreviewChunkingPayload(TypedDict):
    chunk_overlap: NotRequired[int]
    chunk_size: NotRequired[int]
    languages: NotRequired[list[str]]
    separators: NotRequired[list[str]]
    strategy: NotRequired[str]
    token_limit: NotRequired[int]


class PreviewChunkingRequest(TypedDict):
    chunking_config: NotRequired[PreviewChunkingPayload]
    text: NotRequired[str]


class PreviewChunkingStats(TypedDict):
    avg_chars: NotRequired[int]
    count: NotRequired[int]
    max_chars: NotRequired[int]
    min_chars: NotRequired[int]
    stddev_chars: NotRequired[int]
    truncated_to: NotRequired[int]


class PromoteUserToSystemAdminRequest(TypedDict):
    email: NotRequired[str]
    user_id: NotRequired[str]


class RemoteModelCheckRequest(TypedDict):
    apiKey: NotRequired[str]
    appSecret: NotRequired[str]
    baseUrl: NotRequired[str]
    customHeaders: NotRequired[dict[str, str]]
    dimension: NotRequired[int]
    extraConfig: NotRequired[dict[str, str]]
    interfaceType: NotRequired[str]
    modelId: NotRequired[str]
    modelName: str
    provider: NotRequired[str]
    source: NotRequired[str]


class RevokeSystemAdminRequest(TypedDict):
    user_id: str


class SearchMessagesRequest(TypedDict):
    limit: NotRequired[int]
    mode: NotRequired[str]
    query: str
    session_ids: NotRequired[list[str]]


class StorageCheckRequest(TypedDict):
    cos: NotRequired[COSEngineConfig]
    ks3: NotRequired[KS3EngineConfig]
    minio: NotRequired[MinIOEngineConfig]
    obs: NotRequired[OBSEngineConfig]
    oss: NotRequired[OSSEngineConfig]
    provider: NotRequired[str]
    s3: NotRequired[S3EngineConfig]
    tos: NotRequired[TOSEngineConfig]


class StorageCheckResponse(TypedDict):
    bucket_created: NotRequired[bool]
    message: NotRequired[str]
    ok: NotRequired[bool]


class StorageEngineStatusItem(TypedDict):
    allowed: NotRequired[bool]
    available: NotRequired[bool]
    description: NotRequired[str]
    name: NotRequired[str]


class TestProviderRequest(TypedDict):
    parameters: NotRequired[WebSearchProviderParameters]
    provider: str


class TestStoreRequest(TypedDict):
    connection_config: ConnectionConfig
    engine_type: RetrieverEngineType


class TextRelationExtractionRequest(TypedDict):
    model_id: str
    tags: list[str]
    text: str


class UpdateAgentRequest(TypedDict):
    avatar: NotRequired[str]
    config: NotRequired[CustomAgentConfig]
    description: NotRequired[str]
    name: NotRequired[str]


class UpdateChunkRequest(TypedDict):
    chunk_index: NotRequired[int]
    content: NotRequired[str]
    embedding: NotRequired[list[float]]
    end_at: NotRequired[int]
    image_info: NotRequired[str]
    is_enabled: NotRequired[bool]
    start_at: NotRequired[int]


class UpdateModelRequest(TypedDict):
    description: NotRequired[str]
    display_name: NotRequired[str]
    name: NotRequired[str]
    parameters: NotRequired[ModelParameters]
    source: NotRequired[ModelSource]
    type: NotRequired[ModelType]


class UpdateProviderRequest(TypedDict):
    description: NotRequired[str]
    is_default: NotRequired[bool]
    name: NotRequired[str]
    parameters: NotRequired[WebSearchProviderParameters]


class UpdateStoreRequest(TypedDict):
    name: str


class UpdateSystemSettingRequest(TypedDict):
    value: NotRequired[Any]


class AddMemberRequest(TypedDict):
    email: str
    role: TenantRole


class AddSimilarQuestionsRequest(TypedDict):
    similar_questions: list[str]


class CreateInvitationRequest(TypedDict):
    email: str
    message: NotRequired[str]
    role: TenantRole


class CreateInviteLinkRequest(TypedDict):
    message: NotRequired[str]
    role: TenantRole


class CreateTenantRequest(TypedDict):
    description: NotRequired[str]
    name: str


class InvitationLookupRequest(TypedDict):
    token: str


class InvitationLookupResponse(TypedDict):
    expires_at: NotRequired[str]
    role: NotRequired[TenantRole]
    tenant_id: NotRequired[int]
    tenant_name: NotRequired[str]


class RegisterByInviteRequest(TypedDict):
    email: str
    password: str
    token: str
    username: str


class UpdateLastFAQImportResultDisplayStatusRequest(TypedDict):
    display_status: Literal['open', 'close']


class UpdateMemberRoleRequest1(TypedDict):
    role: TenantRole


class UpdateMyPreferencesRequest(TypedDict):
    enable_memory: NotRequired[bool]
    last_active_tenant_id: NotRequired[int]


class AttachmentUpload(TypedDict):
    data: NotRequired[str]
    file_name: NotRequired[str]
    file_size: NotRequired[int]


class CreateSessionRequest(TypedDict):
    description: NotRequired[str]
    title: NotRequired[str]


class ImageAttachment(TypedDict):
    caption: NotRequired[str]
    data: NotRequired[str]
    url: NotRequired[str]


class MentionedItemRequest(TypedDict):
    id: NotRequired[str]
    kb_type: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[str]


class SearchKnowledgeRequest(TypedDict):
    knowledge_base_id: NotRequired[str]
    knowledge_base_ids: NotRequired[list[str]]
    knowledge_ids: NotRequired[list[str]]
    query: str


class StopSessionRequest(TypedDict):
    message_id: str


class BatchDeleteRequest(TypedDict):
    delete_all: NotRequired[bool]
    ids: NotRequired[list[str]]


class WikiLintIssue(TypedDict):
    auto_fixable: NotRequired[bool]
    description: NotRequired[str]
    page_slug: NotRequired[str]
    severity: NotRequired[WikiLintIssueSeverity]
    target_slug: NotRequired[str]
    type: NotRequired[WikiLintIssueType]


class AppError(TypedDict):
    code: NotRequired[ErrorCode]
    details: NotRequired[Any]
    message: NotRequired[str]


class AuditLog(TypedDict):
    action: NotRequired[AuditAction]
    actor_role: NotRequired[str]
    actor_user_id: NotRequired[str]
    created_at: NotRequired[str]
    details: NotRequired[list[int]]
    id: NotRequired[int]
    outcome: NotRequired[AuditOutcome]
    request_method: NotRequired[str]
    request_path: NotRequired[str]
    target_id: NotRequired[str]
    target_type: NotRequired[str]
    target_user_id: NotRequired[str]
    tenant_id: NotRequired[int]


class ChunkingConfig(TypedDict):
    child_chunk_size: NotRequired[int]
    chunk_overlap: NotRequired[int]
    chunk_size: NotRequired[int]
    enable_parent_child: NotRequired[bool]
    languages: NotRequired[list[str]]
    parent_chunk_size: NotRequired[int]
    parser_engine_rules: NotRequired[list[ParserEngineRule]]
    separators: NotRequired[list[str]]
    strategy: NotRequired[str]
    token_limit: NotRequired[int]


class CredentialsConfig(TypedDict):
    weknoracloud: NotRequired[WeKnoraCloudCredentials]


class DataSource(TypedDict):
    config: NotRequired[list[int]]
    conflict_strategy: NotRequired[str]
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    error_message: NotRequired[str]
    id: NotRequired[str]
    knowledge_base_id: NotRequired[str]
    last_sync_at: NotRequired[str]
    last_sync_cursor: NotRequired[list[int]]
    last_sync_result: NotRequired[list[int]]
    latest_sync_log: NotRequired[SyncLog]
    name: NotRequired[str]
    status: NotRequired[str]
    sync_deletions: NotRequired[bool]
    sync_log_retention_days: NotRequired[int]
    sync_mode: NotRequired[str]
    sync_schedule: NotRequired[str]
    tenant_id: NotRequired[int]
    total_items_synced: NotRequired[int]
    type: NotRequired[str]
    updated_at: NotRequired[str]


class ExtractConfig(TypedDict):
    enabled: NotRequired[bool]
    nodes: NotRequired[list[GraphNode]]
    relations: NotRequired[list[GraphRelation]]
    tags: NotRequired[list[str]]
    text: NotRequired[str]


class FAQBatchUpsertPayload(TypedDict):
    dry_run: NotRequired[bool]
    entries: list[FAQEntryPayload]
    knowledge_id: NotRequired[str]
    mode: NotRequired[Literal['append', 'replace']]
    task_id: NotRequired[str]


class FAQConfig(TypedDict):
    index_mode: NotRequired[FAQIndexMode]
    question_index_mode: NotRequired[FAQQuestionIndexMode]


class FAQEntryFieldsBatchUpdate(TypedDict):
    by_id: NotRequired[dict[str, FAQEntryFieldsUpdate]]
    by_tag: NotRequired[dict[str, FAQEntryFieldsUpdate]]
    exclude_ids: NotRequired[list[int]]


class InviteMemberRequest(TypedDict):
    representative_user_id: NotRequired[str]
    role: OrgMemberRole
    tenant_id: NotRequired[int]
    user_id: NotRequired[str]


class JoinByOrganizationIDRequest(TypedDict):
    message: NotRequired[str]
    organization_id: str
    role: NotRequired[OrgMemberRole]


class Knowledge(TypedDict):
    channel: NotRequired[str]
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    description: NotRequired[str]
    embedding_model_id: NotRequired[str]
    enable_status: NotRequired[str]
    error_message: NotRequired[str]
    file_hash: NotRequired[str]
    file_name: NotRequired[str]
    file_path: NotRequired[str]
    file_size: NotRequired[int]
    file_type: NotRequired[str]
    id: NotRequired[str]
    knowledge_base_id: NotRequired[str]
    knowledge_base_name: NotRequired[str]
    last_faq_import_result: NotRequired[list[int]]
    metadata: NotRequired[list[int]]
    parse_status: NotRequired[str]
    pending_subtasks_count: NotRequired[int]
    processed_at: NotRequired[str]
    source: NotRequired[str]
    storage_size: NotRequired[int]
    summary_status: NotRequired[str]
    tag_id: NotRequired[str]
    tenant_id: NotRequired[int]
    title: NotRequired[str]
    type: NotRequired[str]
    updated_at: NotRequired[str]


class KnowledgeProcessOverrides(TypedDict):
    asr_config: NotRequired[ASRConfig]
    chunking_config: NotRequired[ChunkingConfig]
    enable_multimodel: NotRequired[bool]
    extract_config: NotRequired[ExtractConfig]
    graph_enabled: NotRequired[bool]
    parser_engine_rules: NotRequired[list[ParserEngineRule]]
    question_generation_config: NotRequired[QuestionGenerationConfig]
    vlm_config: NotRequired[VLMConfig]


class ListMembersResponse(TypedDict):
    members: NotRequired[list[OrganizationMemberResponse]]
    total: NotRequired[int]


class ListOrganizationsResponse(TypedDict):
    organizations: NotRequired[list[OrganizationResponse]]
    resource_counts: NotRequired[ResourceCountsByOrgResponse]
    total: NotRequired[int]


class MCPService(TypedDict):
    advanced_config: NotRequired[MCPAdvancedConfig]
    auth_config: NotRequired[MCPAuthConfig]
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    description: NotRequired[str]
    enabled: NotRequired[bool]
    env_vars: NotRequired[MCPEnvVars]
    headers: NotRequired[MCPHeaders]
    id: NotRequired[str]
    is_builtin: NotRequired[bool]
    name: NotRequired[str]
    stdio_config: NotRequired[MCPStdioConfig]
    tenant_id: NotRequired[int]
    transport_type: NotRequired[MCPTransportType]
    updated_at: NotRequired[str]
    url: NotRequired[str]


class ManualKnowledgePayload(TypedDict):
    channel: NotRequired[str]
    content: NotRequired[str]
    process_config: NotRequired[KnowledgeProcessOverrides]
    status: NotRequired[str]
    tag_id: NotRequired[str]
    title: NotRequired[str]


class Membership(TypedDict):
    role: NotRequired[TenantRole]
    tenant_id: NotRequired[int]
    tenant_name: NotRequired[str]


class RetrieverEngineParams(TypedDict):
    retriever_engine_type: NotRequired[RetrieverEngineType]
    retriever_type: NotRequired[RetrieverType]


class RetrieverEngines(TypedDict):
    engines: NotRequired[list[RetrieverEngineParams]]


class Session(TypedDict):
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    description: NotRequired[str]
    id: NotRequired[str]
    is_pinned: NotRequired[bool]
    last_request_state: NotRequired[SessionLastRequestState]
    pinned_at: NotRequired[str]
    tenant_id: NotRequired[int]
    title: NotRequired[str]
    updated_at: NotRequired[str]
    user_id: NotRequired[str]


class StorageEngineConfig(TypedDict):
    cos: NotRequired[COSEngineConfig]
    default_provider: NotRequired[str]
    ks3: NotRequired[KS3EngineConfig]
    local: NotRequired[LocalEngineConfig]
    minio: NotRequired[MinIOEngineConfig]
    obs: NotRequired[OBSEngineConfig]
    oss: NotRequired[OSSEngineConfig]
    s3: NotRequired[S3EngineConfig]
    tos: NotRequired[TOSEngineConfig]


class Tenant(TypedDict):
    api_key: NotRequired[str]
    business: NotRequired[str]
    chat_history_config: NotRequired[ChatHistoryConfig]
    context_config: NotRequired[ContextConfig]
    created_at: NotRequired[str]
    credentials: NotRequired[CredentialsConfig]
    deleted_at: NotRequired[DeletedAt]
    description: NotRequired[str]
    id: NotRequired[int]
    name: NotRequired[str]
    parser_engine_config: NotRequired[ParserEngineConfig]
    retrieval_config: NotRequired[RetrievalConfig]
    retriever_engines: NotRequired[RetrieverEngines]
    status: NotRequired[str]
    storage_engine_config: NotRequired[StorageEngineConfig]
    storage_quota: NotRequired[int]
    storage_used: NotRequired[int]
    updated_at: NotRequired[str]
    web_search_config: NotRequired[WebSearchConfig]


class ToolCall(TypedDict):
    args: NotRequired[dict[str, Any]]
    duration: NotRequired[int]
    id: NotRequired[str]
    name: NotRequired[str]
    provider_metadata: NotRequired[ToolCallMetadata]
    reflection: NotRequired[str]
    result: NotRequired[ToolResult]


class User(TypedDict):
    avatar: NotRequired[str]
    can_access_all_tenants: NotRequired[bool]
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    email: NotRequired[str]
    id: NotRequired[str]
    is_active: NotRequired[bool]
    is_system_admin: NotRequired[bool]
    preferences: NotRequired[UserPreferences]
    tenant: NotRequired[Tenant]
    tenant_id: NotRequired[int]
    updated_at: NotRequired[str]
    username: NotRequired[str]


class UserInfo(TypedDict):
    avatar: NotRequired[str]
    can_access_all_tenants: NotRequired[bool]
    created_at: NotRequired[str]
    email: NotRequired[str]
    id: NotRequired[str]
    is_active: NotRequired[bool]
    is_system_admin: NotRequired[bool]
    preferences: NotRequired[UserPreferences]
    tenant_id: NotRequired[int]
    updated_at: NotRequired[str]
    username: NotRequired[str]


class WebSearchProviderEntity(TypedDict):
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    description: NotRequired[str]
    id: NotRequired[str]
    is_default: NotRequired[bool]
    name: NotRequired[str]
    parameters: NotRequired[WebSearchProviderParameters]
    provider: NotRequired[WebSearchProviderType]
    tenant_id: NotRequired[int]
    updated_at: NotRequired[str]


class WikiConfig(TypedDict):
    extraction_granularity: NotRequired[WikiExtractionGranularity]
    ingest_batch_size: NotRequired[int]
    ingest_map_parallel: NotRequired[int]
    ingest_reduce_parallel: NotRequired[int]
    max_pages_per_ingest: NotRequired[int]
    synthesis_model_id: NotRequired[str]


class WikiGraphData(TypedDict):
    edges: NotRequired[list[WikiGraphEdge]]
    meta: NotRequired[WikiGraphMeta]
    nodes: NotRequired[list[WikiGraphNode]]


class WikiLogEntry(TypedDict):
    action: NotRequired[str]
    created_at: NotRequired[str]
    doc_title: NotRequired[str]
    id: NotRequired[int]
    knowledge_base_id: NotRequired[str]
    knowledge_id: NotRequired[str]
    pages_affected: NotRequired[list[WikiLogPageRef]]
    summary: NotRequired[str]
    tenant_id: NotRequired[int]


class WikiLogEntryListResponse(TypedDict):
    entries: NotRequired[list[WikiLogEntry]]
    next_cursor: NotRequired[str]


class WikiPage(TypedDict):
    aliases: NotRequired[list[str]]
    chunk_refs: NotRequired[list[str]]
    content: NotRequired[str]
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    id: NotRequired[str]
    in_links: NotRequired[list[str]]
    knowledge_base_id: NotRequired[str]
    out_links: NotRequired[list[str]]
    page_metadata: NotRequired[list[int]]
    page_type: NotRequired[str]
    slug: NotRequired[str]
    source_refs: NotRequired[list[str]]
    status: NotRequired[str]
    summary: NotRequired[str]
    tenant_id: NotRequired[int]
    title: NotRequired[str]
    updated_at: NotRequired[str]
    version: NotRequired[int]


class WikiPageIssue(TypedDict):
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    description: NotRequired[str]
    id: NotRequired[str]
    issue_type: NotRequired[str]
    knowledge_base_id: NotRequired[str]
    reported_by: NotRequired[str]
    slug: NotRequired[str]
    status: NotRequired[str]
    suspected_knowledge_ids: NotRequired[list[str]]
    tenant_id: NotRequired[int]
    updated_at: NotRequired[str]


class WikiPageListResponse(TypedDict):
    page: NotRequired[int]
    page_size: NotRequired[int]
    pages: NotRequired[list[WikiPage]]
    total: NotRequired[int]
    total_pages: NotRequired[int]


class WikiStats(TypedDict):
    is_active: NotRequired[bool]
    orphan_count: NotRequired[int]
    pages_by_type: NotRequired[dict[str, int]]
    pending_issues: NotRequired[int]
    pending_tasks: NotRequired[int]
    recent_updates: NotRequired[list[WikiPage]]
    total_links: NotRequired[int]
    total_pages: NotRequired[int]


class GetStorageEngineStatusResponse(TypedDict):
    allowed_providers: NotRequired[list[str]]
    engines: NotRequired[list[StorageEngineStatusItem]]
    minio_env_available: NotRequired[bool]


class ListSystemAdminsResponse(TypedDict):
    admins: NotRequired[list[UserInfo]]
    total: NotRequired[int]


class PreviewChunkingResponse(TypedDict):
    chunks: NotRequired[list[PreviewChunkResult]]
    profile: NotRequired[DocProfile]
    rejected: NotRequired[list[TierRejection]]
    selected_tier: NotRequired[StrategyTier]
    stats: NotRequired[PreviewChunkingStats]
    tier_chain: NotRequired[list[StrategyTier]]


class AuditLogListResponse(TypedDict):
    data: NotRequired[list[AuditLog]]
    next_cursor: NotRequired[int]
    success: NotRequired[bool]


class CreateKnowledgeQARequest(TypedDict):
    agent_enabled: NotRequired[bool]
    agent_id: NotRequired[str]
    attachment_uploads: NotRequired[list[AttachmentUpload]]
    channel: NotRequired[str]
    disable_title: NotRequired[bool]
    enable_memory: NotRequired[bool]
    images: NotRequired[list[ImageAttachment]]
    knowledge_base_ids: NotRequired[list[str]]
    knowledge_ids: NotRequired[list[str]]
    mentioned_items: NotRequired[list[MentionedItemRequest]]
    query: str
    summary_model_id: NotRequired[str]
    web_search_enabled: NotRequired[bool]


class WikiLintReport(TypedDict):
    health_score: NotRequired[int]
    issues: NotRequired[list[WikiLintIssue]]
    knowledge_base_id: NotRequired[str]
    stats: NotRequired[WikiStats]
    summary: NotRequired[str]


class AgentStep(TypedDict):
    iteration: NotRequired[int]
    reasoning_content: NotRequired[str]
    thought: NotRequired[str]
    timestamp: NotRequired[str]
    tool_calls: NotRequired[list[ToolCall]]


class KnowledgeBase(TypedDict):
    asr_config: NotRequired[ASRConfig]
    chunk_count: NotRequired[int]
    chunking_config: NotRequired[ChunkingConfig]
    created_at: NotRequired[str]
    creator_id: NotRequired[str]
    creator_name: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    description: NotRequired[str]
    embedding_model_id: NotRequired[str]
    extract_config: NotRequired[ExtractConfig]
    faq_config: NotRequired[FAQConfig]
    id: NotRequired[str]
    image_processing_config: NotRequired[ImageProcessingConfig]
    indexing_strategy: NotRequired[IndexingStrategy]
    is_pinned: NotRequired[bool]
    is_processing: NotRequired[bool]
    is_temporary: NotRequired[bool]
    knowledge_count: NotRequired[int]
    name: NotRequired[str]
    pinned_at: NotRequired[str]
    processing_count: NotRequired[int]
    question_generation_config: NotRequired[QuestionGenerationConfig]
    share_count: NotRequired[int]
    storage_config: NotRequired[StorageConfig]
    storage_provider_config: NotRequired[StorageProviderConfig]
    summary_model_id: NotRequired[str]
    tenant_id: NotRequired[int]
    type: NotRequired[str]
    updated_at: NotRequired[str]
    vector_store_id: NotRequired[str]
    vlm_config: NotRequired[VLMConfig]
    wiki_config: NotRequired[WikiConfig]


class KnowledgeBaseConfig(TypedDict):
    chunking_config: NotRequired[ChunkingConfig]
    faq_config: NotRequired[FAQConfig]
    image_processing_config: NotRequired[ImageProcessingConfig]
    indexing_strategy: NotRequired[IndexingStrategy]
    wiki_config: NotRequired[WikiConfig]


class LoginResponse(TypedDict):
    active_tenant: NotRequired[Tenant]
    memberships: NotRequired[list[Membership]]
    message: NotRequired[str]
    refresh_token: NotRequired[str]
    success: NotRequired[bool]
    token: NotRequired[str]
    user: NotRequired[User]


class Message(TypedDict):
    agent_duration_ms: NotRequired[int]
    agent_steps: NotRequired[list[AgentStep]]
    attachments: NotRequired[list[MessageAttachment]]
    channel: NotRequired[str]
    content: NotRequired[str]
    created_at: NotRequired[str]
    deleted_at: NotRequired[DeletedAt]
    id: NotRequired[str]
    images: NotRequired[list[MessageImage]]
    is_completed: NotRequired[bool]
    is_fallback: NotRequired[bool]
    knowledge_id: NotRequired[str]
    knowledge_references: NotRequired[list[SearchResult]]
    mentioned_items: NotRequired[list[MentionedItem]]
    request_id: NotRequired[str]
    role: NotRequired[str]
    session_id: NotRequired[str]
    updated_at: NotRequired[str]


class RegisterResponse(TypedDict):
    message: NotRequired[str]
    success: NotRequired[bool]
    tenant: NotRequired[Tenant]
    user: NotRequired[User]


class UpdateKnowledgeBaseRequest(TypedDict):
    config: NotRequired[KnowledgeBaseConfig]
    description: NotRequired[str]
    name: str


class GenerateTitleRequest(TypedDict):
    messages: list[Message]
